language: python

python: 3.3

env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=pep257
  - TOXENV=cover

matrix:
  allow_failures:
    - env: TOXENV=py34
    - env: TOXENV=cover
  fast_finish: true

install:
  - pip install tox

script:
  - tox
